#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export ZLE_RPROMPT_INDENT=-1

# folder shortcuts
export MY="${HOME}/src/${USER}"
export CLOUD="${HOME}/Mobile Documents/com~apple~CloudDocs"
